/**
 * The shapes the app works with.
 *
 * These were previously generated by Prisma from schema.prisma. Firestore has
 * no schema and generates nothing, so they are written out by hand — which
 * makes them the single source of truth for what a document contains, and the
 * thing to update when a field is added.
 *
 * Field names, types and optionality match the old Postgres columns exactly, so
 * that every page and component consuming them kept working untouched through
 * the migration.
 */

export type Ingredient = { amt: string; txt: string };
export type HoursRow = { day: string; time: string };

export type Category = {
  id: string;
  slug: string;
  label: string;
  order: number;
  createdAt: Date;
  updatedAt: Date;
};

export type MenuItem = {
  id: string;
  slug: string;
  name: string;
  tamil: string;
  price: number;
  blurb: string;
  accent: string;
  imageUrl: string | null;
  /** "veg" | "hot" | "star" */
  tags: string[];
  published: boolean;
  order: number;

  // Recipe
  time: string;
  serves: string;
  level: string;
  ingredients: Ingredient[];
  steps: string[];
  note: string;

  categoryId: string;
  /** Denormalised from the category, because Firestore cannot join. */
  categorySlug: string;
  categoryLabel: string;

  createdAt: Date;
  updatedAt: Date;
};

/** What `include: { category: true }` produces. */
export type MenuItemWithCategory = MenuItem & {
  category: { id: string; slug: string; label: string };
};

export type Post = {
  id: string;
  slug: string;
  title: string;
  category: string;
  excerpt: string;
  imageUrl: string | null;
  readMins: number;
  body: unknown[];
  published: boolean;
  publishedAt: Date;
  createdAt: Date;
  updatedAt: Date;
};

export type Page = {
  id: string;
  slug: string;
  title: string;
  intro: string;
  body: unknown[];
  published: boolean;
  createdAt: Date;
  updatedAt: Date;
};

export type CakeOption = {
  id: string;
  kind: string;
  key: string;
  label: string;
  note: string;
  price: number;
  /** Size multiplier, stored x100 so it stays an integer (100 = 1.0x). */
  multiplier: number;
  tierColor: string;
  frostColor: string;
  heightPx: number;
  order: number;
  active: boolean;
  createdAt: Date;
  updatedAt: Date;
};

export type Package = {
  id: string;
  name: string;
  price: string;
  unit: string;
  items: string[];
  hero: boolean;
  order: number;
  active: boolean;
  createdAt: Date;
  updatedAt: Date;
};

export type Media = {
  id: string;
  filename: string;
  url: string;
  mimeType: string;
  size: number;
  width: number | null;
  height: number | null;
  alt: string;
  createdAt: Date;
};

export type Settings = {
  /** Always 1. Kept for compatibility; the document itself lives at settings/main. */
  id: number;

  cafeName: string;
  tamilName: string;
  tagline: string;
  heroLine1: string;
  heroLine2: string;
  heroEyebrow: string;
  heroBadge: string;
  heroTrust: string;
  heroSide: string;

  logoUrl: string;
  logoDarkUrl: string;
  heroVideoUrl: string;
  heroPosterUrl: string;
  storyImage1Url: string;
  storyImage2Url: string;

  ownerName: string;
  ownerRole: string;
  ownerPhotoUrl: string;
  ownerNote: string;

  phone: string;
  whatsapp: string;
  email: string;
  addressL1: string;
  addressL2: string;
  addressL3: string;
  mapsQuery: string;

  hours: HoursRow[];
  marquee: string[];

  updatedAt: Date;
};

/** Defaults for a database that has never been seeded. */
export const SETTINGS_DEFAULTS: Omit<Settings, "id" | "updatedAt"> = {
  cafeName: "Kapi Coast",
  tamilName: "காபி கோஸ்ட்",
  tagline: "Degree filter kapi · Kadak chai · Chaat & street eats",
  heroLine1: "Filter coffee, hot chai and street food made fresh in front of you.",
  heroLine2:
    "An easy place to sit — from the first cup of the morning to the last of the night.",
  heroEyebrow: "OMR · Kazhipattur",
  heroBadge: "Open till 11 pm",
  heroTrust: "Freshly brewed all day · Dine in or takeaway",
  heroSide: "Made fresh · Served warm",

  logoUrl: "/img/logo.png",
  logoDarkUrl: "/img/logo-nav.png",
  heroVideoUrl: "/video/kapi-hills.mp4",
  heroPosterUrl: "/img/hero-poster.jpg",
  storyImage1Url: "",
  storyImage2Url: "",

  ownerName: "",
  ownerRole: "Owner",
  ownerPhotoUrl: "/img/owner-placeholder.webp",
  ownerNote: "",

  phone: "+91 98400 00000",
  whatsapp: "919840000000",
  email: "hello@kapicoast.in",
  addressL1: "105, OMR Road, Kazhipattur Village",
  addressL2: "Vaniyanchavadi, Kalipattur",
  addressL3: "Chennai, Tamil Nadu 603103",
  mapsQuery:
    "105, OMR Rd, Kazhipattur Village, Vaniyanchavadi, Kalipattur, Chennai, Tamil Nadu 603103",

  hours: [],
  marquee: [],
};
