/**
 * Recipes for the menu.
 *
 * IMPORTANT — read before trusting these.
 * These are standard preparations written to match each item on the printed
 * menu. They are NOT a transcription of how Kapi Coast actually cooks. Quantities
 * are sensible defaults; the counter's real ratios, brands and timings will
 * differ. Everything here is editable from Admin -> Menu & recipes.
 *
 * Items with no recipe (bottled drinks) carry a short serving note instead, so
 * the panel says something honest rather than inventing a method.
 *
 * Format: [amount, ingredient] pairs, then ordered steps, then a counter note.
 */

const r = (time, serves, level, ing, steps, note = "") => ({
  time,
  serves,
  level,
  ingredients: ing.map(([amt, txt]) => ({ amt, txt })),
  steps,
  note,
});

/** Bottled or packaged — nothing is made, so no method is claimed. */
const bottled = (note) => ({
  time: "",
  serves: "1 bottle",
  level: "",
  ingredients: [],
  steps: [],
  note,
});

export const RECIPES = {
  /* ------------------------------------------------------- hot drinks -- */

  "filter-coffee": r("10 min", "1 tumbler", "Easy",
    [["3 tbsp", "coarse filter coffee powder (70:30 coffee to chicory)"],
     ["120 ml", "water, just off the boil"],
     ["150 ml", "full-fat milk"],
     ["2 tsp", "sugar, or to taste"]],
    ["Spoon the coffee powder into the upper chamber of the steel filter and level it with the pressing disc. Do not pack it down hard — the water needs to find its way through.",
     "Pour the hot water over the disc, cover, and leave it alone. The decoction takes 15–20 minutes to drip through.",
     "Boil the milk and keep it hot.",
     "Pour about a quarter tumbler of decoction into the tumbler, add sugar, then top with hot milk.",
     "Pull it: pour back and forth between tumbler and davara from a height until it froths and the heat is even."],
    "Decoction made more than a couple of hours ago turns bitter. We brew through the day rather than keep a flask standing."),

  "masala-tea": r("8 min", "1 cup", "Easy",
    [["1½ tsp", "strong CTC tea dust"],
     ["100 ml", "water"],
     ["150 ml", "full-fat milk"],
     ["2 tsp", "sugar"],
     ["1 pinch", "crushed cardamom, clove, ginger and a little cinnamon"]],
    ["Bring the water to a boil with the crushed spices and let them open up for a minute.",
     "Add the tea dust and boil hard for a minute until the water goes deep red.",
     "Pour in the milk and sugar and bring it back to a rolling boil.",
     "Let it rise, pull the pan off, let it settle, and repeat twice — that is what makes it kadak.",
     "Strain into the cup through a fine mesh."],
    "The spice is crushed fresh each morning. Ready-made masala powder goes flat within a day."),

  "ginger-tea": r("8 min", "1 cup", "Easy",
    [["1 inch", "fresh ginger, crushed"],
     ["1½ tsp", "CTC tea dust"],
     ["100 ml", "water"],
     ["150 ml", "full-fat milk"],
     ["2 tsp", "sugar"]],
    ["Crush the ginger properly — bruised, not sliced, so it gives up its juice.",
     "Boil it in the water for two minutes until the water smells sharp.",
     "Add the tea dust and boil for another minute.",
     "Add milk and sugar, bring to a boil, and let it rise twice.",
     "Strain hot into the cup."],
    "Add the ginger to the water, never to the milk — going in late will split it."),

  "black-coffee": r("5 min", "1 cup", "Easy",
    [["2 tbsp", "filter coffee decoction, or 1 tsp instant coffee"],
     ["200 ml", "hot water"],
     ["1–2 tsp", "sugar, optional"]],
    ["Take the decoction into the cup, or dissolve the instant coffee in a splash of hot water first so it does not clump.",
     "Top with hot water — hot, not boiling, or it scalds and turns bitter.",
     "Sweeten to taste and serve straight away."],
    "Ask for it strong and we use a heavier pour of decoction rather than less water."),

  "black-tea": r("5 min", "1 cup", "Easy",
    [["1 tsp", "tea dust"],
     ["200 ml", "water"],
     ["1–2 tsp", "sugar, optional"],
     ["1 wedge", "lemon, optional"]],
    ["Boil the water.",
     "Add the tea dust, take the pan off the heat and cover it for two minutes. Boiling tea dust hard without milk makes it harsh.",
     "Strain into the cup.",
     "Add sugar, and lemon only if asked — lemon and milk do not go together."],
    "Left standing, black tea keeps brewing in the pot and goes bitter. We make it to order."),

  "lemon-honey-tea": r("5 min", "1 cup", "Easy",
    [["200 ml", "hot water"],
     ["1 tsp", "tea dust, optional"],
     ["2 tsp", "honey"],
     ["½", "lemon, juiced"],
     ["1 slice", "fresh ginger, optional"]],
    ["Steep the tea dust and ginger in hot water for two minutes, then strain. For a plain lemon-honey, skip the tea.",
     "Let the water sit for a minute — honey stirred into boiling water loses its character.",
     "Stir in the honey until dissolved.",
     "Squeeze in the lemon last, off the heat, and serve."],
    "Squeeze the lemon at the end. Boiled lemon juice turns dull and slightly bitter."),

  "milk": r("5 min", "1 glass", "Easy",
    [["250 ml", "full-fat milk"],
     ["1–2 tsp", "sugar, optional"],
     ["1 pinch", "cardamom, optional"]],
    ["Bring the milk to a boil over medium heat, stirring so it does not catch on the base.",
     "Let it rise once, then pull it off.",
     "Sweeten if asked and add a pinch of cardamom.",
     "Serve hot in a glass."],
    "Boiled fresh each time. Milk reheated twice tastes of the pan."),

  "horlicks": r("5 min", "1 glass", "Easy",
    [["3 tbsp", "Horlicks powder"],
     ["250 ml", "hot milk"],
     ["1 tsp", "sugar, optional"]],
    ["Put the powder in the glass with two spoons of hot milk and work it into a smooth paste. This is the step that prevents lumps.",
     "Pour in the rest of the hot milk while stirring.",
     "Taste before adding sugar — the powder is already sweetened.",
     "Serve hot."],
    "Malt powder tipped straight into a full glass always lumps. Paste first, every time."),

  "boost": r("5 min", "1 glass", "Easy",
    [["3 tbsp", "Boost powder"],
     ["250 ml", "hot milk"],
     ["1 tsp", "sugar, optional"]],
    ["Make a smooth paste with the powder and a little hot milk.",
     "Add the remaining hot milk in a steady stream, stirring as you go.",
     "Check the sweetness before adding any sugar.",
     "Serve hot, stirred well from the bottom."],
    "Boost settles faster than Horlicks. Give it a stir before it goes out."),

  "badam-milk": r("20 min", "1 glass", "Medium",
    [["12", "almonds, soaked overnight and peeled"],
     ["250 ml", "full-fat milk"],
     ["2 tsp", "sugar"],
     ["4–5 strands", "saffron"],
     ["1 pinch", "cardamom powder"]],
    ["Grind the peeled almonds to a fine paste with a splash of milk.",
     "Warm the saffron in a spoon of milk so the colour comes out.",
     "Bring the rest of the milk to a boil, lower the heat and stir in the almond paste.",
     "Simmer five minutes until it thickens slightly, stirring so it does not catch.",
     "Add sugar, saffron milk and cardamom. Serve hot."],
    "Peel the almonds. The skin makes the drink grainy and slightly bitter."),

  /* ------------------------------------------------------ cold drinks -- */

  "cold-coffee": r("10 min", "1 tall glass", "Easy",
    [["60 ml", "strong coffee decoction, cooled"],
     ["200 ml", "chilled full-fat milk"],
     ["2 tbsp", "sugar"],
     ["1 scoop", "vanilla ice cream, optional"],
     ["6–8", "ice cubes"]],
    ["Make the decoction ahead and chill it. Warm coffee melts the ice and thins the glass.",
     "Blend the decoction, milk, sugar and ice until the top goes pale and foamy — about a minute.",
     "Add the ice cream and pulse briefly. Over-blending makes it flat.",
     "Pour into a chilled tall glass and serve at once."],
    "The froth falls within a few minutes. It is blended when ordered, not held ready."),

  "coke-400-ml": bottled("Served chilled from the fridge, opened at the counter. Nothing prepared in the kitchen."),
  "fanta-400-ml": bottled("Served chilled from the fridge, opened at the counter. Nothing prepared in the kitchen."),
  "sprite-400-ml": bottled("Served chilled from the fridge, opened at the counter. Nothing prepared in the kitchen."),
  "glass-bottle": bottled("Returnable glass bottle — Coke, Fanta, Sprite or Limca, whichever is cold. Ask at the counter for what is in today."),
  "water-bottle-1-l": bottled("Sealed one-litre packaged drinking water. We open it at your table so you can see the seal."),

  /* ------------------------------------------------------ fresh juice -- */

  "watermelon": r("5 min", "1 glass", "Easy",
    [["500 g", "ripe watermelon, cubed and deseeded"],
     ["1 tsp", "lemon juice"],
     ["1 pinch", "black salt, optional"],
     ["4–5", "ice cubes"]],
    ["Cube the melon and pick out the seeds.",
     "Blend on its own — watermelon is mostly water and needs nothing added.",
     "Strain through a coarse sieve if you want it clear; leave it as it is for body.",
     "Add lemon, a pinch of black salt if asked, and pour over ice."],
    "No sugar and no water. If it is not sweet enough, the melon was not ripe and we cut another."),

  "pomegranate": r("10 min", "1 glass", "Medium",
    [["2 large", "pomegranates, deseeded"],
     ["1 tsp", "lemon juice"],
     ["1 pinch", "black salt, optional"]],
    ["Deseed the pomegranates, keeping out every bit of white pith.",
     "Blend the seeds briefly — just enough to release the juice, no longer.",
     "Strain through a fine sieve, pressing gently.",
     "Add lemon and serve chilled, without ice so it does not thin."],
    "Blend it short. Crushed pomegranate seeds turn the juice bitter within seconds."),

  "apple": r("5 min", "1 glass", "Easy",
    [["3 medium", "apples, cored"],
     ["1 tsp", "lemon juice"],
     ["4–5", "ice cubes"]],
    ["Core the apples and cut them up. Leave the skin on for colour and flavour.",
     "Press or blend with a little water, then strain.",
     "Stir in the lemon juice at once — this is what keeps it from browning.",
     "Pour over ice and serve immediately."],
    "Apple juice browns within minutes. It goes out as soon as it is pressed."),

  "orange": r("5 min", "1 glass", "Easy",
    [["4–5", "oranges"],
     ["1 tsp", "sugar, optional"],
     ["1 pinch", "salt, optional"]],
    ["Roll the oranges under your palm first — it loosens the segments and yields more juice.",
     "Halve and squeeze on a press.",
     "Strain out the seeds but leave a little pulp.",
     "Serve fresh, chilled, without ice."],
    "Squeeze gently. Pressing into the white pith is what makes fresh orange juice bitter."),

  "musk-melon": r("5 min", "1 glass", "Easy",
    [["500 g", "ripe musk melon, cubed"],
     ["1 tsp", "lemon juice"],
     ["1 tsp", "sugar, optional"],
     ["4–5", "ice cubes"]],
    ["Scoop out the seeds and cube the flesh.",
     "Blend smooth. It is naturally thick, so a splash of water helps.",
     "Add lemon to lift it — melon alone tastes flat.",
     "Pour over ice and serve cold."],
    "Ripe melon needs no sugar. We taste it before adding any."),

  "dragon-fruit": r("5 min", "1 glass", "Easy",
    [["2", "dragon fruit, peeled"],
     ["100 ml", "chilled water or coconut water"],
     ["1 tsp", "lemon juice"],
     ["1 tsp", "sugar, optional"],
     ["4–5", "ice cubes"]],
    ["Halve the fruit and scoop the flesh straight out of the skin.",
     "Blend with the chilled water until smooth.",
     "Do not strain — the tiny black seeds are meant to stay in.",
     "Add lemon and sugar to taste, pour over ice."],
    "Dragon fruit is mild on its own. The lemon is what makes it taste of anything."),

  "pineapple": r("8 min", "1 glass", "Easy",
    [["½", "ripe pineapple, peeled and cored"],
     ["1 tsp", "lemon juice"],
     ["1–2 tsp", "sugar, to taste"],
     ["1 pinch", "black salt, optional"],
     ["4–5", "ice cubes"]],
    ["Peel the pineapple, cut out the eyes, and remove the hard core — the core is what makes it harsh.",
     "Blend the flesh with a splash of water.",
     "Strain through a coarse sieve to hold back the fibre.",
     "Balance with lemon, sugar and a pinch of black salt, then pour over ice."],
    "Always cut the core out. Left in, it scratches the throat."),

  /* ------------------------------------------------------- milkshakes -- */

  "oreo": r("5 min", "1 tall glass", "Easy",
    [["6", "Oreo biscuits"],
     ["250 ml", "chilled full-fat milk"],
     ["2 scoops", "vanilla ice cream"],
     ["1 tbsp", "sugar, optional"]],
    ["Keep one biscuit aside for the top.",
     "Blend the rest with the milk and ice cream until thick and speckled.",
     "Do not over-blend — the shake should still have flecks of biscuit through it.",
     "Pour into a tall glass, crush the last biscuit over the top and serve with a wide straw."],
    "Blend with the cream still on the biscuit. Scraping it off is a waste of the best part."),

  "lotus-biscoff": r("5 min", "1 tall glass", "Easy",
    [["3", "Biscoff biscuits"],
     ["1½ tbsp", "Biscoff spread"],
     ["250 ml", "chilled full-fat milk"],
     ["2 scoops", "vanilla ice cream"]],
    ["Smear a little of the spread inside the glass — it streaks the sides as the shake goes in.",
     "Blend the rest of the spread with the milk, ice cream and two biscuits.",
     "Pour into the prepared glass.",
     "Crumble the last biscuit over the top."],
    "The spread is already sweet. Adding sugar on top of it makes the shake cloying."),

  "kitkat": r("5 min", "1 tall glass", "Easy",
    [["2 fingers", "KitKat"],
     ["250 ml", "chilled full-fat milk"],
     ["2 scoops", "vanilla ice cream"],
     ["1 tbsp", "chocolate syrup"]],
    ["Line the glass with chocolate syrup.",
     "Blend one and a half KitKat fingers with the milk and ice cream until smooth.",
     "Pour in, keeping the syrup lines visible.",
     "Stand the remaining half finger in the top."],
    "Blend the wafer properly. Left in chunks it sinks and clogs the straw."),

  "chocolate": r("5 min", "1 tall glass", "Easy",
    [["2 tbsp", "cocoa powder or drinking chocolate"],
     ["250 ml", "chilled full-fat milk"],
     ["2 scoops", "vanilla ice cream"],
     ["2 tbsp", "sugar"],
     ["1 tbsp", "chocolate syrup, for the glass"]],
    ["Mix the cocoa and sugar with a splash of warm milk into a smooth paste — cocoa will not blend into cold milk on its own.",
     "Blend the paste with the remaining chilled milk and the ice cream.",
     "Line the glass with syrup and pour.",
     "Serve cold with a wide straw."],
    "Cocoa needs the warm paste step or the shake ends up with dry powder in the bottom."),

  "vanilla": r("5 min", "1 tall glass", "Easy",
    [["250 ml", "chilled full-fat milk"],
     ["2 scoops", "vanilla ice cream"],
     ["1 tbsp", "sugar"],
     ["¼ tsp", "vanilla essence"]],
    ["Blend everything together until smooth and frothy.",
     "Keep it short — thirty seconds is enough, longer and it thins out.",
     "Pour into a chilled glass and serve straight away."],
    "The simplest shake on the board, so the milk has to be properly cold to start with."),

  "rose-milk": r("5 min", "1 glass", "Easy",
    [["3 tbsp", "rose syrup"],
     ["250 ml", "chilled full-fat milk"],
     ["4–5", "ice cubes"],
     ["1 tbsp", "sabja seeds, soaked, optional"]],
    ["Pour the rose syrup into the base of the glass.",
     "Add the chilled milk and stir well from the bottom so the syrup lifts.",
     "Add soaked sabja seeds if you want them.",
     "Top with ice and serve pink and cold."],
    "Boiled milk must be fully cold before the syrup goes in, or the colour goes muddy."),

  "badam-milk-cold": r("20 min", "1 glass", "Medium",
    [["12", "almonds, soaked and peeled"],
     ["250 ml", "full-fat milk"],
     ["2 tsp", "sugar"],
     ["4–5 strands", "saffron"],
     ["1 pinch", "cardamom powder"],
     ["4–5", "ice cubes"]],
    ["Grind the peeled almonds to a fine paste with a little milk.",
     "Boil the rest of the milk, stir in the paste and simmer five minutes.",
     "Add sugar, saffron and cardamom, then take it off the heat.",
     "Cool completely and refrigerate — this is not a drink to rush with ice.",
     "Serve chilled over a little ice."],
    "Made in the morning and kept cold. Ice added to warm badam milk just waters it down."),

  /* ---------------------------------------------------- andhra snacks -- */

  "mirchi-bajji": r("20 min", "4 pieces", "Medium",
    [["4", "long bajji chillies"],
     ["1 cup", "gram flour (besan)"],
     ["2 tbsp", "rice flour"],
     ["¼ tsp", "carom seeds (ajwain)"],
     ["1 pinch", "baking soda"],
     ["to taste", "salt"],
     ["as needed", "oil, for deep frying"]],
    ["Slit each chilli down one side and scrape out the seeds — that is where most of the heat sits.",
     "Whisk the gram flour, rice flour, ajwain, soda and salt with water into a batter thick enough to coat the back of a spoon.",
     "Heat the oil to medium-high. A drop of batter should rise straight back up.",
     "Dip each chilli, let the excess run off, and slide it into the oil.",
     "Fry until pale gold and crisp, turning once. Drain on paper.",
     "Serve hot with onion and a squeeze of lemon."],
    "Rice flour in the batter is what keeps it crisp on the plate instead of going soft in two minutes."),

  "medhu-vada": r("30 min + soaking", "6 vadas", "Hard",
    [["1 cup", "urad dal, soaked 3–4 hours"],
     ["1 tsp", "cumin seeds"],
     ["1 inch", "ginger, chopped fine"],
     ["2", "green chillies, chopped"],
     ["a few", "curry leaves, torn"],
     ["to taste", "salt"],
     ["as needed", "oil, for deep frying"]],
    ["Drain the dal completely and grind it with as little water as you can — the batter must be thick and fluffy, never pourable.",
     "Beat the batter by hand for a few minutes until a spoonful floats in a bowl of water. That float test is the whole recipe.",
     "Fold in the cumin, ginger, chillies, curry leaves and salt just before frying.",
     "Wet your palm, take a ball of batter, flatten it and make a hole through the middle with your thumb.",
     "Slide into medium-hot oil and fry until deep golden on both sides.",
     "Drain and serve hot with chutney and sambar."],
    "Salt goes in at the last moment. Added early it draws out water and the batter will not hold its shape."),

  "masala-vada": r("30 min + soaking", "6 vadas", "Medium",
    [["1 cup", "chana dal, soaked 2 hours"],
     ["2", "green chillies"],
     ["1 inch", "ginger"],
     ["1 small", "onion, chopped fine"],
     ["a few", "curry leaves and coriander, chopped"],
     ["¼ tsp", "fennel seeds"],
     ["to taste", "salt"],
     ["as needed", "oil, for deep frying"]],
    ["Set aside two spoons of the soaked dal whole — they give the vada its bite.",
     "Grind the rest coarsely with the chillies, ginger and fennel, using no water at all.",
     "Mix in the reserved whole dal, onion, curry leaves, coriander and salt.",
     "Shape into flat patties on your palm.",
     "Fry in medium-hot oil until deep golden and crisp right through.",
     "Drain and serve hot."],
    "Ground too fine it turns into a paste and fries heavy. Coarse is the point."),

  "onion-bonda": r("25 min", "6 pieces", "Medium",
    [["2 medium", "potatoes, boiled and mashed"],
     ["1 large", "onion, chopped fine"],
     ["2", "green chillies, chopped"],
     ["1 tsp", "mustard seeds"],
     ["a few", "curry leaves"],
     ["1 cup", "gram flour (besan)"],
     ["2 tbsp", "rice flour"],
     ["1 pinch", "turmeric and salt"],
     ["as needed", "oil, for deep frying"]],
    ["Temper mustard seeds and curry leaves in a little oil, add the onion and chillies and cook until soft.",
     "Mix into the mashed potato with turmeric and salt. Cool, then roll into balls.",
     "Whisk the gram flour, rice flour and salt with water into a smooth coating batter.",
     "Dip each ball to coat fully — any bare patch will burst in the oil.",
     "Fry in medium-hot oil until golden all over.",
     "Drain and serve hot with chutney."],
    "Let the filling cool before shaping. Warm potato thins the batter and the bonda falls apart."),

  "raw-banana-bajji": r("20 min", "6 pieces", "Easy",
    [["1 large", "raw banana (plantain)"],
     ["1 cup", "gram flour (besan)"],
     ["2 tbsp", "rice flour"],
     ["¼ tsp", "carom seeds"],
     ["1 pinch", "turmeric, chilli powder and salt"],
     ["1 pinch", "baking soda"],
     ["as needed", "oil, for deep frying"]],
    ["Peel and slice the plantain into thin rounds and drop them straight into water so they do not darken.",
     "Whisk the flours with the spices, soda, salt and water into a coating batter.",
     "Pat the slices dry, dip and fry in medium-hot oil.",
     "Turn once, fry until golden, and drain.",
     "Serve hot with coconut chutney."],
    "Slice thin. Thick plantain stays raw in the middle while the batter is already brown."),

  "aloo-bajji": r("20 min", "6 pieces", "Easy",
    [["2 medium", "potatoes"],
     ["1 cup", "gram flour (besan)"],
     ["2 tbsp", "rice flour"],
     ["¼ tsp", "carom seeds"],
     ["1 pinch", "chilli powder, turmeric and salt"],
     ["1 pinch", "baking soda"],
     ["as needed", "oil, for deep frying"]],
    ["Slice the potatoes into thin rounds and keep them in water until you fry.",
     "Whisk a smooth batter with the flours, spices, soda, salt and water.",
     "Pat each slice dry — wet potato makes the batter slide off.",
     "Dip and fry in medium-hot oil until golden and crisp.",
     "Drain and serve hot."],
    "Fry in small batches. Crowding the pan drops the oil temperature and the bajji drinks it up."),

  "onion-pakoda": r("20 min", "1 plate", "Easy",
    [["3 large", "onions, sliced thin"],
     ["1 cup", "gram flour (besan)"],
     ["3 tbsp", "rice flour"],
     ["2", "green chillies, chopped"],
     ["a few", "curry leaves"],
     ["1 pinch", "chilli powder and turmeric"],
     ["to taste", "salt"],
     ["as needed", "oil, for deep frying"]],
    ["Mix the sliced onion with salt and leave it ten minutes. It will release its own water.",
     "Add the flours, chillies, curry leaves and spices and mix with your fingers.",
     "Use that released water to bring it together. Add extra water only a few drops at a time — the mix should be barely damp, not a batter.",
     "Drop rough clusters into medium-hot oil.",
     "Fry until deep golden and crisp, then drain.",
     "Serve hot."],
    "The wetter the mix, the softer the pakoda. Almost no added water is the trick."),

  "samosa": r("45 min", "6 samosas", "Hard",
    [["2 cups", "plain flour (maida)"],
     ["4 tbsp", "oil or ghee, for the dough"],
     ["½ tsp", "carom seeds"],
     ["3 medium", "potatoes, boiled and roughly crushed"],
     ["½ cup", "green peas"],
     ["1 tsp", "cumin seeds"],
     ["1 tsp", "coriander seeds, crushed"],
     ["½ tsp", "garam masala and amchur"],
     ["to taste", "salt"],
     ["as needed", "oil, for deep frying"]],
    ["Rub the oil into the flour with the carom seeds and salt until it clumps when pressed. Add just enough water to make a stiff dough, then rest it 20 minutes.",
     "Temper cumin and crushed coriander, add peas, then the crushed potato, garam masala, amchur and salt. Cook a few minutes and cool.",
     "Roll a ball of dough into an oval and cut it in half. Form a cone from each half, sealing the straight edge with water.",
     "Fill, press the top edge closed firmly, and make sure there is no gap.",
     "Fry on LOW heat for 12–15 minutes until pale gold, then raise the heat at the end to crisp them.",
     "Drain and serve hot with chutney."],
    "Low and slow is what gives the flaky, blistered shell. Hot oil browns the outside while the pastry inside stays raw."),

  "french-fries": r("25 min", "1 plate", "Medium",
    [["3 large", "potatoes"],
     ["to taste", "salt"],
     ["as needed", "oil, for deep frying"],
     ["optional", "peri-peri or chaat masala"]],
    ["Cut the potatoes into even batons and rinse them under cold water until it runs clear — washing off the surface starch is what stops them sticking.",
     "Soak 20 minutes, then dry them completely.",
     "Fry once at medium heat until soft but still pale. Lift out and rest.",
     "Just before serving, fry again in hot oil until golden and crisp.",
     "Drain, salt immediately while hot, and toss with masala if asked."],
    "Two fries, not one. A single fry gives you either a soggy chip or a burnt one."),

  "punugulu-14-pc": r("20 min", "14 pieces", "Easy",
    [["2 cups", "leftover idly or dosa batter, slightly sour"],
     ["1 small", "onion, chopped fine"],
     ["2", "green chillies, chopped"],
     ["1 inch", "ginger, chopped"],
     ["2 tbsp", "rice flour"],
     ["1 tsp", "cumin seeds"],
     ["a few", "curry leaves"],
     ["to taste", "salt"],
     ["as needed", "oil, for deep frying"]],
    ["Use batter that has soured a day — fresh batter makes flat, oily punugulu.",
     "Stir in the onion, chillies, ginger, cumin, curry leaves, rice flour and salt. It should be thick enough to drop from a spoon and hold.",
     "Heat oil to medium-hot.",
     "Drop small spoonfuls in and fry until deep golden and round.",
     "Drain and serve hot with coconut or peanut chutney."],
    "This is what yesterday's dosa batter is for. Nothing is wasted."),

  /* ----------------------------------------------------------- tiffin -- */

  "idly-2": r("20 min + fermenting", "2 idlies", "Medium",
    [["3 cups", "idly rice"],
     ["1 cup", "urad dal"],
     ["1 tsp", "fenugreek seeds"],
     ["to taste", "salt"],
     ["to serve", "coconut chutney and sambar"]],
    ["Soak the rice, and separately the dal with fenugreek, for four hours.",
     "Grind the dal first to a light, fluffy paste, then the rice to a slightly coarse one. Combine by hand — the warmth of your hand helps it ferment.",
     "Add salt, cover and leave overnight to rise and smell faintly sour.",
     "Grease the idly plates, pour in the batter and steam for 10–12 minutes.",
     "Test with a damp finger: it should come away clean. Rest two minutes before unmoulding.",
     "Serve hot with chutney and sambar."],
    "Fermenting is weather, not clock. In Chennai heat the batter is ready sooner than any recipe says."),

  "idly-vada": r("15 min", "2 idly + 1 vada", "Medium",
    [["2", "steamed idlies"],
     ["1", "medhu vada, fried fresh"],
     ["1 bowl", "sambar, hot"],
     ["2 tbsp", "coconut chutney"]],
    ["Steam the idlies fresh and keep them covered so they do not dry.",
     "Fry the vada to order — a vada fried in advance goes leathery.",
     "Plate two idlies and one vada together.",
     "Serve with hot sambar and coconut chutney on the side."],
    "The most ordered plate on the board. The vada is always fried after you order, which is why it takes a few minutes."),

  "sambar-idly": r("15 min", "1 plate", "Easy",
    [["2–3", "steamed idlies"],
     ["1 bowl", "hot sambar"],
     ["1 tsp", "ghee, optional"],
     ["to garnish", "coriander"]],
    ["Steam the idlies fresh and let them stand a minute so they firm up.",
     "Heat the sambar until it is properly hot, not just warm.",
     "Place the idlies in a deep bowl and ladle sambar over until they are half submerged.",
     "Give them a minute to drink it in before serving.",
     "Finish with ghee and coriander."],
    "Idlies straight from the steamer break apart in sambar. A short rest first keeps them whole."),

  "sambar-vada": r("15 min", "1 plate", "Medium",
    [["2", "medhu vadas, fried fresh"],
     ["1 bowl", "hot sambar"],
     ["to garnish", "onion and coriander"]],
    ["Fry the vadas until deep golden and drain them well.",
     "Heat the sambar through.",
     "Put the vadas in a bowl and pour the hot sambar over.",
     "Leave them two minutes so the middle softens while the edges hold.",
     "Top with chopped onion and coriander and serve."],
    "Dunked too early the vada turns to mush. Two minutes is the window."),

  "podi-idly": r("15 min", "1 plate", "Easy",
    [["3–4", "small idlies"],
     ["2 tbsp", "idly podi (milagai podi)"],
     ["2 tbsp", "gingelly oil or ghee"],
     ["to serve", "coconut chutney"]],
    ["Steam the idlies and cut them in halves or quarters.",
     "Mix the podi with the oil or ghee into a loose paste.",
     "Toss the idly pieces through until every side is coated.",
     "For a better version, pan-fry the coated pieces a minute until the edges catch.",
     "Serve hot with chutney."],
    "Gingelly oil is the traditional choice and ghee is the richer one. Both are on the counter."),

  /* ------------------------------------------------------------ chaat -- */

  "pani-puri": r("20 min", "6 puris", "Medium",
    [["6", "ready puris"],
     ["1 cup", "mint-coriander pani"],
     ["½ cup", "boiled potato, mashed"],
     ["½ cup", "boiled white peas"],
     ["2 tbsp", "tamarind-date chutney"],
     ["1 tsp", "chaat masala and black salt"],
     ["1 tbsp", "chopped onion, optional"]],
    ["Blend mint, coriander, green chilli, ginger and tamarind with cold water. Season with black salt and chaat masala, then chill it hard.",
     "Mash the potato with the peas, a little chaat masala and salt.",
     "Tap a hole in the top of each puri with your thumb.",
     "Fill with the potato mix, a little onion, a touch of sweet chutney.",
     "Dip full into the cold pani and eat it in one — there is no second chance with a filled puri."],
    "The pani has to be genuinely cold. Room-temperature pani is the difference between good and forgettable."),

  "dahi-puri": r("15 min", "6 puris", "Easy",
    [["6", "ready puris"],
     ["½ cup", "thick curd, whisked and chilled"],
     ["½ cup", "boiled potato, mashed"],
     ["2 tbsp", "tamarind-date chutney"],
     ["1 tbsp", "green chutney"],
     ["2 tbsp", "fine sev"],
     ["1 tsp", "chaat masala"],
     ["to garnish", "coriander and pomegranate"]],
    ["Whisk the curd smooth with a pinch of salt and sugar and keep it cold.",
     "Crack the tops of the puris and fill with mashed potato.",
     "Spoon over both chutneys, then the chilled curd.",
     "Dust with chaat masala, cover with sev, and finish with coriander and pomegranate.",
     "Serve at once, before the puris soften."],
    "Assembled when you order. Made even a minute early, the puri goes soft and the whole point is lost."),

  "bhel-puri": r("10 min", "1 plate", "Easy",
    [["2 cups", "puffed rice (murmura)"],
     ["½ cup", "fine sev"],
     ["1 small", "onion, chopped fine"],
     ["1 small", "tomato, chopped and deseeded"],
     ["1 small", "boiled potato, cubed"],
     ["2 tbsp", "tamarind-date chutney"],
     ["1 tbsp", "green chutney"],
     ["1 tsp", "chaat masala"],
     ["1", "lemon"],
     ["2", "crushed puris"]],
    ["Dry-roast the puffed rice a minute if it has gone limp — it must be crisp to start with.",
     "Deseed the tomato so it does not water the bhel down.",
     "Tip everything except the sev and crushed puris into a wide bowl.",
     "Toss quickly with both chutneys, chaat masala and a squeeze of lemon.",
     "Top with sev and crushed puri and serve immediately."],
    "Mixed to order and eaten straight away. Bhel that has sat five minutes is a different dish."),

  "pappadi-chaat": r("15 min", "1 plate", "Easy",
    [["8–10", "pappadi (flat crisp crackers)"],
     ["½ cup", "thick curd, whisked and chilled"],
     ["½ cup", "boiled chana or white peas"],
     ["1 small", "boiled potato, cubed"],
     ["2 tbsp", "tamarind-date chutney"],
     ["1 tbsp", "green chutney"],
     ["2 tbsp", "sev"],
     ["1 tsp", "chaat masala and roasted cumin powder"],
     ["to garnish", "onion, coriander, pomegranate"]],
    ["Lay the pappadi out flat on the plate in a single layer.",
     "Scatter over the potato and chana.",
     "Spoon the chilled curd across, then both chutneys.",
     "Dust with chaat masala and roasted cumin.",
     "Finish with sev, onion, coriander and pomegranate. Serve at once."],
    "Curd straight from the fridge, crackers dry until the last second. Assembled early it collapses into a soggy plate."),

  /* ----------------------------------------------------------- snacks -- */

  "bread-omelette": r("10 min", "1 plate", "Easy",
    [["2", "eggs"],
     ["2 slices", "bread"],
     ["1 small", "onion, chopped fine"],
     ["1", "green chilli, chopped"],
     ["1 tbsp", "coriander, chopped"],
     ["1 pinch", "black pepper and salt"],
     ["1 tbsp", "butter or oil"]],
    ["Beat the eggs well with the onion, chilli, coriander, salt and pepper — beat until frothy, that is what makes it fluffy.",
     "Heat butter in a pan and pour in the egg.",
     "As it begins to set, lay the bread slices on top and press them down gently.",
     "Flip so the bread side cooks and the egg wraps around it.",
     "Cook another minute, fold over and serve hot."],
    "Beat properly and cook on medium. High heat gives you a rubbery omelette every time."),

  "veg-sandwich": r("12 min", "1 sandwich", "Easy",
    [["4 slices", "sandwich bread"],
     ["1", "cucumber, tomato and onion, sliced thin"],
     ["1 small", "boiled potato, sliced"],
     ["2 tbsp", "green chutney"],
     ["1 tbsp", "butter"],
     ["1 pinch", "chaat masala and salt"],
     ["2 tbsp", "grated cheese, optional"]],
    ["Butter every slice right to the edges — the butter is what stops the vegetables making the bread soggy.",
     "Spread green chutney over the butter.",
     "Layer cucumber, tomato, onion and potato, seasoning each layer lightly with salt and chaat masala.",
     "Add cheese if asked, close the sandwich and press.",
     "Grill until the outside is crisp and marked, then cut across and serve hot."],
    "Deseed and drain the tomato. That one step is the difference between a crisp sandwich and a wet one."),

  "paneer-sandwich": r("15 min", "1 sandwich", "Medium",
    [["4 slices", "sandwich bread"],
     ["150 g", "paneer, crumbled or cubed"],
     ["1 small", "onion and capsicum, chopped fine"],
     ["1 tsp", "ginger-garlic paste"],
     ["½ tsp", "chilli powder, garam masala and turmeric"],
     ["2 tbsp", "green chutney"],
     ["1 tbsp", "butter"],
     ["2 tbsp", "grated cheese, optional"]],
    ["Sauté the onion and capsicum until they soften, add the ginger-garlic paste and cook off the raw smell.",
     "Add the spices and salt, then fold in the paneer. Cook two minutes only — paneer held on heat goes rubbery.",
     "Cool the filling slightly.",
     "Butter the bread, spread chutney, spoon in the paneer and add cheese if asked.",
     "Grill until crisp and golden. Cut and serve hot."],
    "Take the paneer off the heat while it is still soft. It carries on cooking in the grill."),

  "veg-puff": r("30 min", "4 puffs", "Medium",
    [["1 sheet", "puff pastry, chilled"],
     ["2 medium", "potatoes, boiled and cubed"],
     ["½ cup", "carrot, beans and peas, chopped small"],
     ["1 small", "onion, chopped"],
     ["1 tsp", "ginger-garlic paste"],
     ["½ tsp", "chilli powder and garam masala"],
     ["to taste", "salt"],
     ["1", "egg or milk, for brushing"]],
    ["Cook the onion, then the ginger-garlic paste, then the vegetables with the spices and salt until dry. Any moisture will make the pastry soggy.",
     "Cool the filling completely. This matters more than anything else here.",
     "Cut the chilled pastry into squares, spoon filling onto one half, fold over and press the edges with a fork.",
     "Brush the tops with egg or milk.",
     "Bake at 200°C for 18–20 minutes until puffed and deep golden."],
    "Work with the pastry cold. Once the butter in it softens, the layers stop separating and it bakes flat."),

  "egg-puff": r("30 min", "4 puffs", "Medium",
    [["1 sheet", "puff pastry, chilled"],
     ["2", "eggs, hard-boiled and halved"],
     ["1 large", "onion, sliced"],
     ["1 tsp", "ginger-garlic paste"],
     ["½ tsp", "chilli powder, pepper and garam masala"],
     ["to taste", "salt"],
     ["1", "egg or milk, for brushing"]],
    ["Boil the eggs for exactly nine minutes, cool them in water and peel. Halve them.",
     "Fry the onion until soft and golden, add ginger-garlic paste and the spices, and cook until dry.",
     "Cut the chilled pastry into squares. Put a spoon of masala onion down, then half an egg cut side down.",
     "Fold over, seal the edges firmly and brush the top.",
     "Bake at 200°C for 18–20 minutes until risen and golden brown."],
    "Nine minutes gives a set yolk that is not chalky. Longer and it goes grey at the edge."),

  /* ------------------------------------------------------------- buns -- */

  "jam-bun": r("5 min", "1 bun", "Easy",
    [["1", "soft bun"],
     ["2 tbsp", "mixed fruit jam"],
     ["1 tsp", "butter, optional"]],
    ["Slice the bun almost through, leaving a hinge.",
     "Warm it briefly on the tawa, cut side down, until just heated.",
     "Spread the jam generously right to the edges.",
     "Close, cut in half and serve."],
    "Warm the bun first. Jam on a cold bun sits on top instead of soaking in."),

  "maska-bun": r("5 min", "1 bun", "Easy",
    [["1", "soft bun"],
     ["2 tbsp", "salted butter, soft"]],
    ["Split the bun horizontally.",
     "Toast both cut faces on a hot tawa until lightly golden.",
     "Take it off the heat and lay thick slices of cold butter on straight away — the residual heat should half-melt it, not dissolve it.",
     "Serve immediately with coffee or chai."],
    "The butter goes on off the heat and stays visible. Melted into the bun it just tastes greasy."),

  "bun-butter-jam": r("5 min", "1 bun", "Easy",
    [["1", "soft bun"],
     ["2 tbsp", "salted butter"],
     ["2 tbsp", "mixed fruit jam"]],
    ["Split the bun and toast both faces on the tawa until golden at the edges.",
     "Spread butter on the hot side first and let it sink in.",
     "Spread jam over the butter, thickly.",
     "Close, press lightly, cut and serve warm."],
    "Butter first, jam second. Reversed, the butter never melts in and you taste them separately."),

  "cheese-garlic-bun": r("12 min", "1 bun", "Easy",
    [["1", "soft bun"],
     ["2 tbsp", "butter, softened"],
     ["3 cloves", "garlic, crushed fine"],
     ["1 tbsp", "coriander, chopped"],
     ["3 tbsp", "mozzarella or processed cheese, grated"],
     ["1 pinch", "chilli flakes and oregano"]],
    ["Mash the crushed garlic and coriander into the soft butter with a pinch of salt.",
     "Split the bun and spread the garlic butter thickly over both halves.",
     "Cover with grated cheese and scatter chilli flakes and oregano.",
     "Bake or grill at 200°C for 6–8 minutes until the cheese is molten and bubbling at the edges.",
     "Cut and serve hot, while it still pulls."],
    "Raw crushed garlic, not powder. It is the whole flavour of the bun."),

  /* ------------------------------------------------------------ pizza -- */

  "margherita": r("20 min", "8 inch", "Medium",
    [["1", "8-inch pizza base"],
     ["4 tbsp", "tomato pizza sauce"],
     ["100 g", "mozzarella, grated"],
     ["a few", "fresh basil leaves"],
     ["1 tsp", "olive oil"],
     ["1 pinch", "oregano and chilli flakes"]],
    ["Heat the oven as high as it will go, with the tray inside. A hot tray is what crisps the base.",
     "Spread the sauce thinly, leaving a clear border for the crust.",
     "Scatter the mozzarella evenly — too much and the middle goes wet.",
     "Bake 8–10 minutes until the crust is blistered and the cheese is bubbling with brown spots.",
     "Tear the basil over as it comes out, drizzle with olive oil, and cut."],
    "Basil goes on after baking. In the oven it turns black and tastes of nothing."),

  "veg-pizza": r("25 min", "8 inch", "Medium",
    [["1", "8-inch pizza base"],
     ["4 tbsp", "tomato pizza sauce"],
     ["120 g", "mozzarella, grated"],
     ["½ each", "capsicum, onion and tomato, sliced thin"],
     ["4–5", "sweetcorn spoonfuls and olives, optional"],
     ["1 pinch", "oregano and chilli flakes"]],
    ["Heat the oven fully with the tray inside.",
     "Slice the vegetables thin and pat the tomato dry.",
     "Spread the sauce, add half the cheese, then the vegetables, then the rest of the cheese to hold them down.",
     "Bake 10–12 minutes until the edges are golden and the cheese is bubbling.",
     "Rest a minute before cutting so the cheese sets enough to slice cleanly."],
    "Load it too heavily and the base steams instead of crisping. Restraint makes a better pizza."),

  /* ------------------------------------------------------------ pasta -- */

  "white-sauce-pasta": r("25 min", "1 plate", "Medium",
    [["150 g", "penne or fusilli"],
     ["2 tbsp", "butter"],
     ["2 tbsp", "plain flour"],
     ["400 ml", "milk, warm"],
     ["3 tbsp", "cheese, grated"],
     ["½ each", "capsicum, carrot and sweetcorn"],
     ["2 cloves", "garlic, chopped"],
     ["1 pinch", "black pepper, oregano and chilli flakes"],
     ["to taste", "salt"]],
    ["Boil the pasta in well-salted water until just firm to the bite. Keep a cup of the cooking water.",
     "Melt the butter, add the garlic, then stir in the flour and cook it a minute so it loses the raw taste.",
     "Pour in the warm milk a little at a time, whisking constantly — this is the only way to avoid lumps.",
     "Simmer until it coats the back of a spoon, then stir in the cheese, pepper and salt off the heat.",
     "Sauté the vegetables briefly so they stay crunchy, then fold everything together.",
     "Loosen with the reserved pasta water if it tightens. Serve hot."],
    "White sauce thickens as it stands. The pasta water is there to bring it back."),

  "red-sauce-pasta": r("25 min", "1 plate", "Easy",
    [["150 g", "penne or fusilli"],
     ["4 medium", "tomatoes, blanched and pureed"],
     ["1 small", "onion, chopped fine"],
     ["3 cloves", "garlic, chopped"],
     ["2 tbsp", "olive oil"],
     ["1 tsp", "sugar"],
     ["½ each", "capsicum and sweetcorn"],
     ["1 pinch", "oregano, basil and chilli flakes"],
     ["to taste", "salt and pepper"]],
    ["Boil the pasta in well-salted water until just firm. Save a cup of the water.",
     "Blanch the tomatoes, slip the skins off and blend to a puree.",
     "Cook the garlic and onion in olive oil until soft, then pour in the puree.",
     "Simmer 10 minutes until it darkens and thickens. Add the sugar — it takes the sharp edge off the tomato.",
     "Season, add the vegetables, then toss the pasta through with a splash of the cooking water.",
     "Finish with oregano, basil and chilli flakes."],
    "Give the sauce its ten minutes. Rushed, it stays sour no matter how much sugar goes in."),

  /* ---------------------------------------------------------- cookies -- */

  "butter-cookie": r("30 min", "20 cookies", "Easy",
    [["200 g", "plain flour"],
     ["150 g", "butter, softened"],
     ["80 g", "icing sugar"],
     ["1 tsp", "vanilla essence"],
     ["1 pinch", "salt"]],
    ["Beat the soft butter and icing sugar until pale and light. This is where the melt-in-the-mouth texture comes from.",
     "Mix in the vanilla and salt.",
     "Fold in the flour just until it comes together — working it further develops gluten and makes the cookie tough.",
     "Roll, cut, and chill the shapes 20 minutes.",
     "Bake at 170°C for 12–14 minutes until the edges are barely golden. Cool on the tray; they firm up as they cool."],
    "Take them out looking slightly underdone. They set on the tray, and a browned butter cookie is a hard one."),

  "salt-cookie": r("30 min", "20 cookies", "Easy",
    [["200 g", "plain flour"],
     ["150 g", "butter, softened"],
     ["50 g", "sugar"],
     ["¾ tsp", "fine salt"],
     ["to finish", "flaky salt"]],
    ["Cream the butter and sugar until light.",
     "Beat in the fine salt so it is evenly distributed — pockets of salt are unpleasant.",
     "Fold in the flour to a soft dough and chill it 20 minutes.",
     "Roll, cut, and sprinkle flaky salt over the tops.",
     "Bake at 170°C for 12–14 minutes until pale gold. Cool completely before moving."],
    "Two salts doing two jobs: fine salt through the dough, flakes on top for the bite."),

  "butter-almond": r("35 min", "18 cookies", "Easy",
    [["200 g", "plain flour"],
     ["150 g", "butter, softened"],
     ["80 g", "icing sugar"],
     ["50 g", "almonds, half ground, half halved"],
     ["1 tsp", "vanilla essence"],
     ["1 pinch", "salt"]],
    ["Cream the butter and icing sugar until pale.",
     "Mix in the ground almonds, vanilla and salt.",
     "Fold in the flour lightly to a soft dough and chill 20 minutes.",
     "Shape into rounds and press a halved almond firmly into each top.",
     "Bake at 170°C for 14–16 minutes until the edges colour and the almond is toasted."],
    "Press the almond in properly. A loose one falls off in the jar and the cookie looks bare."),

  /* -------------------------------------------------------- doughnuts -- */

  "chocolate-doughnut": r("2 hr 30 min", "8 doughnuts", "Hard",
    [["300 g", "plain flour"],
     ["7 g", "instant yeast"],
     ["50 g", "sugar"],
     ["150 ml", "warm milk"],
     ["1", "egg"],
     ["40 g", "butter, softened"],
     ["1 pinch", "salt"],
     ["150 g", "dark chocolate, for the glaze"],
     ["as needed", "oil, for frying"]],
    ["Warm the milk to blood temperature — hot milk kills the yeast — and stir in the yeast and a spoon of sugar. Wait until it froths.",
     "Mix with the flour, remaining sugar, egg and salt, then work in the butter. Knead 10 minutes until smooth and elastic.",
     "Prove covered until doubled, about an hour.",
     "Roll to 1 cm, cut rings, and prove again 30 minutes until visibly puffy.",
     "Fry at a steady 170°C, about a minute a side, until golden. Too hot and the middle stays raw.",
     "Cool fully, then dip the tops in melted chocolate and let it set."],
    "Glaze only when completely cold. Warm doughnuts make the chocolate slide straight off."),

  "almond-doughnut": r("2 hr 30 min", "8 doughnuts", "Hard",
    [["300 g", "plain flour"],
     ["7 g", "instant yeast"],
     ["50 g", "sugar"],
     ["150 ml", "warm milk"],
     ["1", "egg"],
     ["40 g", "butter, softened"],
     ["1 pinch", "salt"],
     ["150 g", "white or milk chocolate, for the glaze"],
     ["50 g", "flaked almonds, toasted"]],
    ["Activate the yeast in warm milk with a spoon of sugar until frothy.",
     "Make the dough with flour, sugar, egg, salt and butter, and knead until smooth.",
     "Prove until doubled, roll, cut rings and prove again until puffy.",
     "Fry at 170°C, a minute each side, until evenly golden. Drain.",
     "Toast the flaked almonds separately until fragrant.",
     "Dip the cooled doughnuts in melted chocolate and press the almonds on before it sets."],
    "Toast the almonds. Untoasted flakes taste of nothing and go soft on the glaze."),

  "pistachio-doughnut": r("2 hr 30 min", "8 doughnuts", "Hard",
    [["300 g", "plain flour"],
     ["7 g", "instant yeast"],
     ["50 g", "sugar"],
     ["150 ml", "warm milk"],
     ["1", "egg"],
     ["40 g", "butter, softened"],
     ["1 pinch", "salt"],
     ["150 g", "white chocolate, for the glaze"],
     ["50 g", "pistachios, crushed"]],
    ["Froth the yeast in warm milk with sugar.",
     "Knead into a smooth dough with the flour, sugar, egg, salt and butter.",
     "Prove until doubled, roll, cut and prove again until light.",
     "Fry at 170°C until golden on both sides and drain well.",
     "Melt the white chocolate gently — it catches and seizes faster than dark.",
     "Dip the cooled doughnuts and scatter crushed pistachio over before the glaze sets."],
    "Crush the pistachios coarse. Ground fine they turn to dust and lose the colour."),

  /* ---------------------------------------------------------- dessert -- */

  "brownie": r("45 min", "9 pieces", "Medium",
    [["200 g", "dark chocolate"],
     ["150 g", "butter"],
     ["200 g", "sugar"],
     ["3", "eggs"],
     ["100 g", "plain flour"],
     ["30 g", "cocoa powder"],
     ["1 pinch", "salt"],
     ["50 g", "walnuts, optional"]],
    ["Melt the chocolate and butter together over a pan of simmering water, then let it cool a little.",
     "Whisk the eggs and sugar until thick and pale — this is what gives the shiny crackled top.",
     "Fold the chocolate through, then sift in the flour, cocoa and salt.",
     "Fold only until no streaks remain. Beating now makes it cakey instead of fudgy.",
     "Bake at 170°C for 22–25 minutes. A skewer should come out with moist crumbs, not clean.",
     "Cool fully in the tin before cutting."],
    "Underbake rather than overbake. The middle firms up as it cools, and a fully-baked brownie is just chocolate cake."),

  "brownie-ice-cream": r("10 min", "1 plate", "Easy",
    [["1", "brownie square"],
     ["1 scoop", "vanilla ice cream"],
     ["1 tbsp", "chocolate sauce"],
     ["1 tsp", "crushed nuts, optional"]],
    ["Warm the brownie briefly so it softens — 15 seconds is enough, longer and it dries out.",
     "Put it on a cold plate.",
     "Set the scoop of ice cream beside it, not on top, so it does not melt away before it reaches the table.",
     "Pour warm chocolate sauce over the brownie and scatter the nuts.",
     "Serve immediately."],
    "Warm brownie, cold plate, ice cream last. Ordered together, they arrive together."),

  "vanilla-cake": r("50 min", "1 tea cake", "Medium",
    [["200 g", "plain flour"],
     ["150 g", "butter, softened"],
     ["180 g", "sugar"],
     ["3", "eggs"],
     ["1½ tsp", "baking powder"],
     ["80 ml", "milk"],
     ["2 tsp", "vanilla essence"],
     ["1 pinch", "salt"]],
    ["Have the butter, eggs and milk all at room temperature. Cold ingredients curdle the batter.",
     "Cream the butter and sugar until pale and fluffy, a good five minutes.",
     "Add the eggs one at a time, beating well after each.",
     "Fold in the sifted flour, baking powder and salt alternately with the milk, finishing with flour.",
     "Add the vanilla, pour into a lined tin and bake at 175°C for 35–40 minutes.",
     "Cool ten minutes in the tin, then turn out."],
    "Fold the flour, do not beat it. Overworked batter gives a tight, rubbery crumb."),

  "chocolate-cake": r("50 min", "1 tea cake", "Medium",
    [["180 g", "plain flour"],
     ["50 g", "cocoa powder"],
     ["180 g", "sugar"],
     ["150 g", "butter, softened"],
     ["3", "eggs"],
     ["1½ tsp", "baking powder"],
     ["120 ml", "hot coffee or hot milk"],
     ["1 tsp", "vanilla essence"]],
    ["Sift the cocoa with the flour and baking powder so there are no lumps to chase later.",
     "Cream the butter and sugar until light, then beat in the eggs one at a time.",
     "Fold in the dry ingredients alternately with the hot coffee.",
     "The hot liquid blooms the cocoa and deepens the colour and flavour — it is worth the extra step.",
     "Bake at 175°C for 35–40 minutes until a skewer comes out with a crumb or two.",
     "Cool before slicing."],
    "Coffee does not make it taste of coffee. It makes it taste more of chocolate."),

  "black-forest-cake": r("1 hr", "1 tea cake", "Medium",
    [["1", "chocolate sponge, baked and cooled"],
     ["200 ml", "whipping cream, chilled"],
     ["2 tbsp", "icing sugar"],
     ["100 g", "cherries, halved"],
     ["3 tbsp", "cherry syrup, for soaking"],
     ["50 g", "dark chocolate, shaved"]],
    ["Bake and cool the chocolate sponge completely, then slice it into layers.",
     "Brush each layer with cherry syrup so the cake stays moist.",
     "Whip the chilled cream with icing sugar to soft peaks. Stop there — whipped further it turns grainy.",
     "Layer cream and cherries between the sponge layers.",
     "Cover the top with cream, shave dark chocolate over and finish with a few cherries.",
     "Chill an hour before cutting."],
    "Everything cold: the bowl, the cream, the cake. Warm cream will not hold."),

  "strawberry-cake": r("1 hr", "1 tea cake", "Medium",
    [["1", "vanilla sponge, baked and cooled"],
     ["200 ml", "whipping cream, chilled"],
     ["2 tbsp", "icing sugar"],
     ["150 g", "strawberries, sliced"],
     ["3 tbsp", "sugar syrup, for soaking"],
     ["2 tbsp", "strawberry crush"]],
    ["Cool the sponge fully and slice into layers.",
     "Brush the layers with sugar syrup.",
     "Whip the cream with icing sugar to soft peaks, then fold a little strawberry crush through half of it for colour.",
     "Layer the pink cream and sliced strawberries between the sponge.",
     "Coat the outside with plain cream and arrange strawberries on top.",
     "Chill before slicing."],
    "Slice the strawberries and pat them dry. Wet fruit bleeds into the cream and turns it watery."),

  "pista-cake": r("1 hr", "1 tea cake", "Medium",
    [["1", "vanilla sponge, baked and cooled"],
     ["200 ml", "whipping cream, chilled"],
     ["2 tbsp", "icing sugar"],
     ["80 g", "pistachios, ground, plus extra crushed"],
     ["3 tbsp", "sugar syrup"],
     ["¼ tsp", "cardamom powder"]],
    ["Grind most of the pistachios fine, keeping some crushed for the top.",
     "Slice the cooled sponge into layers and brush with sugar syrup.",
     "Whip the cream to soft peaks with icing sugar, then fold in the ground pistachio and cardamom.",
     "Layer the pistachio cream between the sponge.",
     "Cover the outside and press crushed pistachio around the sides.",
     "Chill an hour before serving."],
    "Cardamom and pistachio belong together. A pinch is enough — more and it takes over."),

  "blueberry-cake": r("1 hr", "1 tea cake", "Medium",
    [["1", "vanilla sponge, baked and cooled"],
     ["200 ml", "whipping cream, chilled"],
     ["2 tbsp", "icing sugar"],
     ["150 g", "blueberries"],
     ["3 tbsp", "blueberry compote or crush"],
     ["3 tbsp", "sugar syrup"]],
    ["Cook a handful of the blueberries with a spoon of sugar into a thick compote and cool it completely.",
     "Slice the cooled sponge and brush the layers with sugar syrup.",
     "Whip the cream with icing sugar to soft peaks.",
     "Layer cream and compote between the sponge, keeping the compote away from the very edge so it does not run.",
     "Cover with cream and top with whole blueberries.",
     "Chill before cutting."],
    "The compote must be cold and thick. Warm or runny, it will bleed through the cream overnight."),
};
